item {
  id: 1
  name: 'center_overpass_right_evasion'
}

item {
  id: 2
  name: 'bus_lane'
}

item {
  id: 3
  name: 'speedlimit_30'
}

item {
  id: 4
  name: 'speedlimit_40'
}

item {
  id: 5
  name: 'speedlimit_50'
}

item {
  id: 6
  name: 'speedlimit_60'
}

item {
  id: 7
  name: 'speedlimit_70'
}

item {
  id: 8
  name: 'speedlimit_80'
}

item {
  id: 9
  name: 'speedlimit_90'
}

item {
  id: 10
  name: 'speedlimit_100'
}

item {
  id: 11
  name: 'speedlimit_110'
}

item {
  id: 12
  name: 'lamp_merering'
}

item {
  id: 13
  name: 'sideroad_violation'
}

item {
  id: 14
  name: 'tail_gating'
}

item {
  id: 15
  name: 'trafficinfo_collrection'
}

item {
  id: 16
  name: 'go_straight'
}

item {
  id: 17
  name: 'go_straight_expressway_entrance'
}

item {
  id: 18
  name: 'go_straight_expressway_exit'
}

item {
  id: 19
  name: 'left_underpass_evasion'
}

item {
  id: 20
  name: 'left_urbanexpressway_entrance'
}

item {
  id: 21
  name: 'left_urbanexpressway_exit'
}

item {
  id: 22
  name: 'overpass_entrance_left'
}

item {
  id: 23
  name: 'right_overpass_entry'
}

item {
  id: 24
  name: 'right_urbanexpressway_entrance'
}

item {
  id: 25
  name: 'right_urbanexpressway_exit'
}

item {
  id: 26
  name: 'rotary_gostraight'
}

item {
  id: 27
  name: 'rotary_left_8'
}

item {
  id: 28
  name: 'rotary_left_11'
}

item {
  id: 29
  name: 'rotary_right'
}

item {
  id: 30
  name: 'rotary_right_1'
}

item {
  id: 31
  name: 'rotary_right_4'
}

item {
  id: 32
  name: 'turn_left'
}

item {
  id: 33
  name: 'turn_left_7to8'
}

item {
  id: 34
  name: 'turn_left_10to11'
}

item {
  id: 35
  name: 'turn_left_unprotected'
}

item {
  id: 36
  name: 'turn_right_1to2'
}

item {
  id: 37
  name: 'turn_right_4to5'
}

item {
  id: 38
  name: 'turn_right'
}

item {
  id: 39
  name: 'uturn'
}